name: Sync PR Labels

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  sync_labels:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Sync labels
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bash .github/workflows/scripts/sync_labels.sh "${{ github.base_ref }}" "${{ github.head_ref }}" ${{ github.event.pull_request.number }}
